name: "Deploy to S3"

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  schedule:
    - cron: '17 14 * * 3'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: ["3.10"]

    steps:
        # Checkout the latest code from the repo
      - name: Checkout repo
        uses: actions/checkout@v2

        # Setup which version of Python to use
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

        # Display the Python version being used
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

        # Update pip
      - name: Update pip
        run: python -m pip install --upgrade pip

        # Install requirements.
      - name: Install requirements
        run: python -m pip install --upgrade -r requirements.txt

        # Create environment variables.
      - name: Create environment variables
        run: python write_config.py --github_access_token ${{ secrets.ACCESS_TOKEN_GITHUB }} --aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --bucket ${{ secrets.AWS_BUCKET }}
        
        # Deploy to S3 Bucket
      - name: Deploy to S3
        run: python update_voters.py --no_print yes